name: Monthly Script Runner

# 触发条件：每月的1号运行
on:
  schedule:
    - cron: "*/5 * * * *"  # 每5分钟执行一次
  workflow_dispatch:  
  push:
    branches:
      - dev

jobs:
  run-scripts:
    if: github.ref == 'refs/heads/dev'  # 限制只在 dev 分支执行
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # 使用 Node.js 18

      # 运行第一个脚本 sync_xlab.js，从接口获取最新数据
      - name: Run sync_xlab.js
        run: node script/sync_xlab.js

      # 运行第二个脚本 update_year_user.js， 更新 rankingList.json
      - name: Run update_year_user.js
        run: node script/update_year_user.js
        env:
          GITHUB_TOKEN: ${{ secrets.SYNC_DATA_TOKEN }}

      # 运行第三个脚本 front-matter.js， 批量创建详情页
      - name: Run front-matter.js
        run: node script/front-matter.js

      # 提交并推送更改
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: Updating data from xlab"
          title: "chore: Updating data from xlab"
          body: "Updating data from xlab, create user homepages in batches"
          branch: "chore/sync-info"
          base: "main"